[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
--show-capture=no
"""
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["{{cookiecutter.project_slug}}"]

[tool.coverage.report]
show_missing = true
fail_under = 100
